The-New-Fork/openfood

.github/pull_request_template.md
None
[JC-1312](https://thenewfork.atlassian.net/browse/JC-1312)
Add a template for pull request, so when everyone trying to create a pull request they know what information should be included in it.
- Added pull_request_template.md file
=> [MAIN] Add pull request template

openfood.py, openfood_env.py, openfood_explorer_lib.py, openfood_komodo_node.py, openfood_ori.py, openfood_utxo_lib.py
[JC-1689](https://thenewfork.atlassian.net/browse/JC-1689)
This PR is to split openfood.py into 4 separate files
Splitting openfood base on its functional, and the result is to separate files into 4 files : openfood.py, openfood_explorer_lib.py, openfood_utxo_lib.py, and openfood_komodo_node.py
-
=> [Main] split openfood.py into 4 separate files

openfood_utxo_lib.py
[JC-1729](https://thenewfork.atlassian.net/browse/JC-1729)
add validation of functions in utxo_libs
to add some validation and datatype for every arguments inside every functions in utxo_libs
=> [Main] add validation of functions in utxo_libs

logs/config.py, openfood_explorer_lib.py, openfood_utxo_lib.py
- [JC-1732](https://thenewfork.atlassian.net/browse/JC-1732)
- [JC-1733](https://thenewfork.atlassian.net/browse/JC-1733)
add logging to explorer and utxo libs
this changes to create logs file base on its own configuration logs for each utxo and explorer libs
- all logs file will be create inside **openfood_lib_dev/logs/**
- utxo_lib_logs.log => for utxo libs
- explorer_lib_logs.log => for explorer libs
=> [Main] add logging to explorer and utxo libs

openfood_env.py
End of sprint sub-lib-version increment
=> sublibversion 57 from sprint end 57

openfood_explorer_lib.py
Fix hardcoded wallet in explorer query.
#24 
Removed the harcoded query wallet in explorer_get_utxos function
Removed the harcoded query wallet in explorer_get_utxos function
=> [Main] Bugfix/harcoded query wallet explorer utxos

openfood.py, openfood_env.py, openfood_explorer_lib.py, openfood_komodo_node.py, openfood_utxo_lib.py, rpclib.py
[JC-1775](https://thenewfork.atlassian.net/browse/JC-1775)
add new function for send to batch address amount dict
list of function that has been added to handle address: amount dict:
- utxo_send_address_amount_dict (_openfood_explorer_lib.py_)
- createrawtx_address_amount_dict (_openfood_explorer_lib.py_)
- createrawtx_wrapper_addr_amount_dict (_openfood_komodo_node.py_)
- createrawtxwithchange_addr_amount_dict (_openfood_komodo_node.py_)
- createrawtransactionwithchange_addr_amount_dict (_rpclib.py_)
- createrawtransaction_addr_amount_dict (_rpclib.py_)
and i put notes like **"""START - New function for address_amount_dict"""** and **"""END - New function for address_amount_dict"""**
=> [Main] add new function for send to batch address amount dict

openfood_env.py
[JC-1894](https://thenewfork.atlassian.net/browse/JC-1894)
add handler EXPLORER_LIST
add handler EXPLORER_LIST
=> [Main] add handler EXPLORER_LIST

openfood_explorer_lib.py
- [JC-1730](https://thenewfork.atlassian.net/browse/JC-1730)
add validation of functions in openfood_explorer_lib.py
to add some validation and datatype for every arguments inside every functions in openfood_explorer_lib.py
=> [Main] add validation functions in openfood_explorer_lib.py

openfood_explorer_lib.py, openfood_komodo_node.py, openfood_log.py, tests/__init__.py, tests/pytest.ini, tests/test_explorer_lib.py
[JC-1909](https://thenewfork.atlassian.net/browse/JC-1909)
[JC-1907](https://thenewfork.atlassian.net/browse/JC-1907)
add explorer_get_network_status function and unittest
- add explorer_get_network_status function to check network status and return result in dictionary
- add unittest for explorer_get_network_status function
How to run test :
- Go to **test folder** (/deploy-samples/simple-working/organization/blocknotify-python/openfood_lib_dev/tests)
- run command **pytest -s test_explorer_lib.py::test_explorer_get_network_status** (to check result from the test)
- run command **pytest -v test_explorer_lib.py::test_explorer_get_network_status** (to run test and to see that test has been passed)
If you want to run test for all function in test_explorer_lib.py, just use : **pytest -v …
=> [Main] add function check network status and unittest

openfood_komodo_node.py, openfood_log.py
- [JC-1734](https://thenewfork.atlassian.net/browse/JC-1734)
add logging to openfood_komodo_node.py, using sentry.io as log framework
this changes to add logging for every function in openfood_komodo_node
Libraries : sentry-sdk==1.9.9 (to install use : **pip install --upgrade sentry-sdk**)
ENV file :
- SENTRY_SDK_DSN="https://198cbc30e54d4fdf85eb5e94fe670450@o4503918670249984.ingest.sentry.io/4503918673985537"
=> [Main] add logging to openfood_komodo_node.py

openfood_explorer_lib.py, openfood_komodo_node.py, openfood_log.py, tests/__init__.py, tests/pytest.ini, tests/test_explorer_lib.py, tests/test_komodo_node.py
[JC-1910](https://thenewfork.atlassian.net/browse/JC-1910)
[JC-1907](https://thenewfork.atlassian.net/browse/JC-1907)
add openfood_komodo_node (getbalance function) and unittest
- add getbalance function to check balance in one organization (account)
- add unittest for getbalance function
How to run test :
- Go to **test folder** (/deploy-samples/simple-working/organization/blocknotify-python/openfood_lib_dev/tests)
- run command **pytest -s test_komodo_node.py::test_get_balance** (to check result from the test)
- run command **pytest -v test_komodo_node.py::test_get_balance** (to run test and to see that test has been passed)
If you want to run test for all function in test_komodo_node.py, just use : **pytest -v test_komodo_node.py**
=> [Main] add openfood_komodo_node function : getbalance

openfood_explorer_lib.py, openfood_komodo_node.py, openfood_log.py, tests/__init__.py, tests/pytest.ini, tests/test_explorer_lib.py
[JC-1908](https://thenewfork.atlassian.net/browse/JC-1908)
[JC-1907](https://thenewfork.atlassian.net/browse/JC-1907)
add get_balance function and unittest
- add explorer_get_balance_final function and divided by 100,000,000
- add unittest for explorer_get_balance_final function
How to run test :
- Go to **test folder** (/deploy-samples/simple-working/organization/blocknotify-python/openfood_lib_dev/tests)
- run command **pytest -s test_explorer_lib.py::test_explorer_get_balance_final** (to check balance before and after convert)
- run command **pytest -v test_explorer_lib.py::test_explorer_get_balance_final** (to run test and to see that test has been passed)
If you want to run test for all function in test_explorer_lib.py, just use : **pytest -v test_explorer_lib.py**
=> [Main] add get balance function and unittest

openfood_explorer_lib.py, openfood_komodo_node.py, tests/test_diagnostics.py, tests/test_komodo_node.py
[JC-1973](https://thenewfork.atlassian.net/browse/JC-1973)
[JC-1907](https://thenewfork.atlassian.net/browse/JC-1907)
diagnostic explorer status with komodo info
to diagnose is there any difference block between explorer status and komodo info
How to run
- Go to **test folder** (/deploy-samples/simple-working/organization/blocknotify-python/openfood_lib_dev/tests)
- run command **pytest -s test_diagnostics.py**
=> [Main] create diagnostics.check_node_status.check_sync

openfood.py, openfood_explorer_lib.py, openfood_komodo_node.py, openfood_lib_diagnostics.py, openfood_log.py, rpclib.py, tests/test_diagnostics.py, tests/test_komodo_node.py
[JC-2054](https://thenewfork.atlassian.net/browse/JC-2054)
- add log level
- add log level
Addition env variable :
- SENTRY_SDK_DSN="https://198cbc30e54d4fdf85eb5e94fe670450@o4503918670249984.ingest.sentry.io/4503918673985537"
- ENVIRONMENT="production"
- LOGGER_LEVEL="info"
=> [Main] Feature/log level

openfood.py
[JC-2187](https://thenewfork.atlassian.net/browse/JC-2187)
The wallet generation for user generated data like locations, certificates, product ids needs to be expanded from the simplicity it currently has.  Adding a type attribute is the first step.
Adds type attribute to json for wallet generation.
=> fixes JC-2187 to add a type attribute to wallet data

openfood.py
[JC-2190](https://thenewfork.atlassian.net/browse/JC-2190)
reverted adding type attribute to wallet
=> fixes JC-2190 removing type attribute

openfood_env.py
Bump openfood_env.py sublib version to 71
=> sublibversion 71

openfood.py
[JC-2263](https://thenewfork.atlassian.net/browse/JC-2263)
Fixes julian dates transactions from marker 0.0001 value to their actual values
string to float and use value passed into function.
=> (bugfix) floats for julian date values instead of marker tx

openfood.py
=> removed typo

openfood_log.py
[JC-2395](https://thenewfork.atlassian.net/browse/JC-2395)
Typo
[JC-2395]: https://thenewfork.atlassian.net/browse/JC-2395?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> JC-2395 typo for env var

openfood_env.py
increment sublibversion to 83 for tx suffix
=> (chore) sublibversion bump 83

openfood_komodo_node.py
[JC-2481](https://thenewfork.atlassian.net/browse/JC-2481)
Adds wrapper methods for sign & send rawtx for foundation oracle creation.
[JC-2481]: https://thenewfork.atlassian.net/browse/JC-2481?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> JC-2481 dependency wrapper functions for foundation oracle starter

openfood.py, openfood_komodo_node.py
[JC-2481](https://thenewfork.atlassian.net/browse/JC-2481)
Functions needed some fixing for the binary data oracle
[JC-2481]: https://thenewfork.atlassian.net/browse/JC-2481?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> JC-2481 fix functions for writing to a binary data oracle
